add support for gradle builds

diff --git a/clusters/common/app-contents/test-scan-namespace/tekton-pipeline.yaml b/clusters/common/app-contents/test-scan-namespace/tekton-pipeline.yaml
--- a/clusters/common/app-contents/test-scan-namespace/tekton-pipeline.yaml
+++ b/clusters/common/app-contents/test-scan-namespace/tekton-pipeline.yaml
@@ -29,5 +29,13 @@ spec:
               # https://vmware.slack.com/archives/C0186SB6ATY/p1644235576354359
               wget -qO- $(params.source-url) | tar xvz -m
               pwd
-              #sleep infinity
-              ./mvnw test
+              MVNW=mvnw
+              GRADLE="build.gradle"
+              if [ -f "$MVNW" ]; then
+                  ./mnvw test
+              elif [ -f "$GRADLE" ]; then
+                  gradle test --debug
+              else 
+                  echo "ERROR: No supported test framework."
+                  exit 1
+              fi
